version: '3.8'

services:
  bot:
    container_name: ${BOT_CONTAINER_NAME}
    build: ./bot
    command: python ./run.py
    restart: always
    ports:
      - ${BOT_PORTS}
    depends_on:
      - database

  database:
    container_name: ${POSTGRES_CONTAINER_NAME}
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_SERVER=${POSTGRES_SERVER}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORTS}